AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', 'AMI']
      InstanceType: t2.micro
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeId: !Ref MyVolume
      Volumes:
        - Device: /dev/sda1
          VolumeId: !Ref MyVolume

  MyVolume:
    Type: 'AWS::EC2::Volume'
    Properties:
      AvailabilityZone: !GetAtt 'MyEC2Instance.AvailabilityZone'
      Size: 30
      SnapshotId: !Ref MySnapshot

  MySnapshot:
    Type: 'AWS::EC2::Snapshot'
    Properties:
      SnapshotId: !Ref SnapshotId

Parameters:
  SnapshotId:
    Type: String
    Description: The ID of the snapshot to use for the volume.

Outputs:
  InstanceId:
    Value: !Ref MyEC2Instance
    Description: The ID of the EC2 instance.
